import Head from "next/head";
import BgImage from "../components/BgImage";
import NameTag from "../components/NameTag";
import LandingCard from "../components/LandingCard";
import Socials from "../components/Socials";

import "bootstrap/dist/css/bootstrap.min.css";
import styles from "../styles/Home.module.css";

export default function Home() {
  //Card data for LandingCard components:
  const aboutCard = {
    style: "about-card",
    image: "/aboutCardImage.jpg",
    header: "",
    body: "Brief description. A longer Bio will live on your about page",
    btnData: { name: "MEET MIKE", link: "/about" },
    id: styles.one,
  };

  const packagesCard = {
    style: "packages-card",
    image: "/packagesCardImage.jpg",
    header: "LET US TAKE YOU ON A TRIP",
    body: "A description of whats included in your service. This will link to the trip packages page. This is kinda like an elevator pitch to give people an idea of what you do",
    btnData: { name: "VIEW TRIP PACKAGES", link: "/packages" },
    id: styles.two,
  };

  const contactCard = {
    style: "contact-card",
    image: "/contactCardImage.jpg",
    header: "PLAN YOUR NEXT TRIP WITH US",
    body: "",
    btnData: { name: "CONTACT", link: "/contact" },
    id: styles.three,
  };

  return (
    <div className="app">
      <Head>
        <title>Blue Mountain Drift</title>
        <meta
          name="Mike Rennie - Fly fishing guide serving Central Virginia"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BgImage />
      <NameTag />
      <LandingCard data={aboutCard} />
      <LandingCard data={packagesCard} />
      <LandingCard data={contactCard} />
      <Socials />
    </div>
  );
}
